### ISSUE TITLE
Implement wage scraping for Indeed and Monster

### ISSUE THREAD

**Issue by PaulMcInnis** [PaulMcInnis/JobFunnel#103]
**Is your feature request related to a problem? Please describe.**
Currently Glassdoor performs wage scraping, but Indeed and monster should do this as well.

**Describe the solution you'd like**
Add scraping for `JobField.WAGE` to indeed and monster scrapers

**Comment by markkvdb** [comment]
This seems to be done in 114568d776b8e2e5519a0cfd2dcd003db06d109d, no?

**Comment by PaulMcInnis** [comment]
@markkvdb  yes, I guess I was expecting my project to move this but it looks like I didn't enable the automation. It'll go in with 3.0.1
