### ISSUE TITLE
Unknown Location Error

### ISSUE THREAD

**Issue by Pittsie72** [PaulMcInnis/JobFunnel#110]
[Files.zip](https://github.com/PaulMcInnis/JobFunnel/files/5318203/Files.zip)

## Description
I have 2 identical .yaml files. Only difference is the location the information is stored and one looks for CFO positions and the other Human Resource. However, the Human Resource has the following error where as the CFO does not:
Traceback (most recent call last):
  File "/home/pittsie/.local/bin/funnel", line 8, in <module>
    sys.exit(main())
  File "/home/pittsie/.local/lib/python3.8/site-packages/jobfunnel/__main__.py", line 28, in main
    job_funnel.run()
  File "/home/pittsie/.local/lib/python3.8/site-packages/jobfunnel/backend/jobfunnel.py", line 86, in run
    self.master_jobs_dict = self.read_master_csv()
  File "/home/pittsie/.local/lib/python3.8/site-packages/jobfunnel/backend/jobfunnel.py", line 405, in read_master_csv
    locale = locale.UNKNOWN
AttributeError: 'NoneType' object has no attribute 'UNKNOWN'

Both files have been attached in a zip

## Expected behavior

Run

## Actual behavior

Error shown above only on Bill.yaml not 2Mom.yaml

## Environment

* Build: 3.0.0
* Operating system and version: Ubuntu 20.04

**Comment by Pittsie72** [comment]
Discovered it was an issue in the CSV

**Comment by PaulMcInnis** [comment]
Ah, yes this would seem to have been caused by an empty column in the CSV.

I think there is value in handling these errors more efficiently though, I will look into improving this.

**Comment by Pittsie72** [comment]
I appreciate it!

I didn't do anything to the csv to add a blank so that's why I was
very confused

**Comment by PaulMcInnis** [comment]
hmm that's not good, was the issue with the CSV that all it got all mixed up? I've been seeing this on my end when something in the job description isn't escaped correctly (it's comma-separated after all).

**Comment by Pittsie72** [comment]
I'm not sure honestly. It looked all normal but I can send it to you if
you'd like

**Comment by PaulMcInnis** [comment]
yeah if you're comfortable please send it over, I'm trying to fix some bugs that are cropping up with CSV updating.

**Comment by PaulMcInnis** [comment]
(I'm most interested in the CSV that caused the failure if you still have it)

**Comment by Pittsie72** [comment]
Attached is the one that caused some errors

**Comment by PaulMcInnis** [comment]
hmm it seems like the attachment didn't make it onto the github, Feel free to send me an email @ paulmcinnis99@gmail.com with the CSV file and I'll take a look.
