### ISSUE TITLE
Bad url search keyword encoding

### ISSUE THREAD

**Issue by PaulMcInnis** [PaulMcInnis/JobFunnel#117]
## Description
We currently pass keywords verbatim, even if they include “+” or other special characters, we should be encoding these so as not to disrupt the url formation. 
  
## Steps to Reproduce

1. Search with any word containing +s such as “C++”

## Expected behavior

We would get a query containing “%” encoded values in place of +s

## Actual behavior

We build a search string with erroneous + chars that breaks the search query url (query is not as intended)

## Environment

* Build: current dev
* Operating system  Ubuntu 18.04

**Comment by PaulMcInnis** [comment]
We should consider using a library that construct urls for us which handles encoding

**Comment by markkvdb** [comment]
This problem is supposed to be fixed in #114

**Comment by PaulMcInnis** [comment]
Marking duplicate #80
