### ISSUE TITLE
Could you please add support for indeed India (https://in.indeed.com/)

### ISSUE THREAD

**Issue by gauthamvr** [PaulMcInnis/JobFunnel#135]
Hi, Could you please add support for indeed India (https://in.indeed.com/). I have been searching job for a month now, and I'm really tired of it. This feature will make my life easier. It would be really helpful if you could add the feature. Else, could you please guide me on how to do it.

**Comment by thebigG** [comment]
Hi there,

It'll be awesome to add India support. I suggest a good place to start is https://github.com/PaulMcInnis/JobFunnel/blob/446e9e06790467d6274e7e69cc505e7b3d982e03/jobfunnel/backend/scrapers/indeed.py#L335

I went to India's Indeed.com and it looks very similar. So you shouldn't have much trouble implementing it if you follow the code snippets above as a template.

Hope this helps.

**Comment by PaulMcInnis** [comment]
added to our compendium of sites to scrape.
