### ISSUE TITLE
Failed to scrape jobs for MonsterScraperCANEng and IndeedScraperCANEng

### ISSUE THREAD

**Issue by ashutosh2909** [PaulMcInnis/JobFunnel#151]
## Description

I have followed the exact process mentioned in the repository to setup my system. However when in am running **funnel load -s my_settings.yaml**, it is not giving any row.
I have setup this code in conda virtual environment 3.9 version. I am using windows 10.

<img width="766" alt="Capture" src="https://user-images.githubusercontent.com/51769717/143460747-badf60b6-049b-48c9-8107-a8554df19823.PNG">

**Comment by PaulMcInnis** [comment]
#148
