### ISSUE TITLE
bad commands;  load, -s in "my_settings.yaml

### ISSUE THREAD

**Issue by rickadams2** [PaulMcInnis/JobFunnel#155]
## Description

Please include a summary of the issue.

I have followed and checked all instructions. This is the output of the script...

```
Bad command "load".
Bad command "-s".
Bad command "my_settings.yaml".
^C

```

List any additional libraries that are affected.

## Steps to Reproduce

1. **First step**

sudo apt install python3-pip  
pip install git+https://github.com/PaulMcInnis/JobFunnel.git  
sudo apt install logtools 
pip install -r requirements.txt  
funnel load -s my_settings.yaml  

  
2. **Second step**

**Input:**

    funnel load -s my_settings.yaml  

 
  

## Expected behavior

A .csv file with filled vacancy data generated via unmodified test YAML script

## Actual behavior

[5122021-JobFunnel-.tar.gz](https://github.com/PaulMcInnis/JobFunnel/files/7655079/5122021-JobFunnel-.tar.gz)
![screen(1)](https://user-images.githubusercontent.com/20592094/144730830-0e3babf7-b585-4cc8-bc74-8d601826e03a.jpg)

**Output from step 2** 

    Bad command "load".
    Bad command "-s".
    Bad command "my_settings.yaml".
    
    ^C

## Environment
Operating system and version: lubuntu-20.04, live distro 
Desktop Environment and/or Window Manager:
Firefox 91.0

##  Used files 
see zip file 
[5122021-JobFunnel-.tar.gz
](https://github.com/PaulMcInnis/JobFunnel/files/7655082/5122021-JobFunnel-.tar.gz)

**Comment by PaulMcInnis** [comment]
Just to confirm, did you download the settings file?

**Comment by rickadams2** [comment]
Hi Paul.  

Yes, I actually downloaded the my_settings.yaml file. See detailed problem description https://github.com/PaulMcInnis/JobFunnel/issues/158

**Comment by PaulMcInnis** [comment]
Why did you file a new issue?
