### ISSUE TITLE
Scraping glassdoor is too slow

### ISSUE THREAD

**Issue by PaulMcInnis** [PaulMcInnis/JobFunnel#18]
Perhaps we should default the configuration to a shallower scrape?

**Comment by PaulMcInnis** [comment]
it appears that it is scraping each job at a time, takes maybe 10 minutes?

**Comment by studentbrad** [comment]
I have looked at alternate methods of doing this.
It seems once you change 'class="jl"' to 'class="jl selected"' there is a reload of a specific part of the job postings page that loads the blurb.
I am looking into where those blurbs come from and if a possible method of requesting that data could improve speed.
