### ISSUE TITLE
Using JobFunnel with PyCharm

### ISSUE THREAD

**Issue by studentbrad** [PaulMcInnis/JobFunnel#24]
![image](https://user-images.githubusercontent.com/15698049/61194976-315b9680-a693-11e9-8e36-68a11750e0b4.png)

I am opening this issue because I think we need a folder `pycharm` for debugging this project.
PyCharm has become a very popular IDE and can really help with debugging this project.
If we can make a folder that gets developers up and running in debug mode in just a few simple steps then I think it is worth doing.

Main benefits of using PyCharm for developing this project:
 - PyCharm has real time break points that are easy to set.
 - PyCharm has an intuitive interface for running expressions in debug mode.
 - PyCharm recognizes URLs in the log output which allows quick "one-click" access to job postings for validation.

**Comment by itSeez** [comment]
Yes please!

This is really useful stuff and we should totally do it. It also seems like you already got it working :1st_place_medal:
