### ISSUE TITLE
Significant lag in CLI

### ISSUE THREAD

**Issue by markkvdb** [PaulMcInnis/JobFunnel#76]
# Significant lag in CLI

## Description

Hi all, 

Installing the latest version of JobFunnel and running `funnel --help` takes a few seconds when opening the first time. Later calls are slightly faster but are arguable still a tad slow.

I know I could have looked into the cause of the problem right now but I'm really low on time as of lately. If this issue still persists when I have more time I will come back to this (kind of a reminder for myself then).

## Steps to Reproduce

1. Fresh install of JobFunnel
2. Call `funnel --help`
3. Wait

## Expected behavior

A few ms delay before showing CLI help information.

## Actual behavior

Significant delay between function call and presented info.

## Environment

* Build: #75 
* Operating system and version: macOS 10.14

**Comment by thebigG** [comment]
That's very strange. I doubt the changes I made will affect the --help prompt's speed. Will be looking into this further when I have time.

**Comment by PaulMcInnis** [comment]
I think this has to do with dependencies mostly, it may be avoided with doing more importing after we do arg-parsing.

**Comment by markkvdb** [comment]
@thebigG it has not been caused by your recent changes. I think it has been here for a long time tbh. Yes, it probably has something to do with the parsing step but this is odd to me, since we are not doing that much parsing to begin with.

**Comment by PaulMcInnis** [comment]
python gets bogged down doing imports before it gets to parsing is my suspicion.

**Comment by PaulMcInnis** [comment]
CLI is acceptably fast at this point in time
