### ISSUE TITLE
[Fix Included] Google Chrome Driver undefined

### ISSUE THREAD

**Issue by phcreery** [PaulMcInnis/JobFunnel#78]
## Description

Google Chrome Driver not defined

## Steps to Correct

Replace line 158 of [jobfunnel/tools/tools.py](https://github.com/PaulMcInnis/JobFunnel/blob/master/jobfunnel/tools/tools.py)
`webdriver.Chrome(ChromeDriverManager().install())`
with
`driver = webdriver.Chrome(ChromeDriverManager().install())`
so function get_webdriver() has a value to return.

Why not a pull request? Too small of a fix

## Environment

* Installed Commit: [cb9f152](https://github.com/PaulMcInnis/JobFunnel/tree/cb9f1529116217f0c7c92df9ca848263debaff1e)
* Operating system and version: Windows 10
* Browser: Google Chrome

**Comment by thebigG** [comment]
I fixed this actually in my last PR #75 
I was the one that forgot that assignment :sweat_smile: 
Thanks so much for bringing this to our attention!

**Comment by phcreery** [comment]
Awesome!! 
My apologies for not researching before submitting an issue.
Will close.
