### ISSUE TITLE
Package for PyPi

### ISSUE THREAD

**Issue by PaulMcInnis** [PaulMcInnis/JobFunnel#99]
**Is your feature request related to a problem? Please describe.**
We are missing some setup items for PyPi:
https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Describe the solution you'd like**
We should make this package conform to PyPi specs so that we can offer a more accessible installation

**Describe alternatives you've considered**
We currently offer installation via github URL, this works totally fine, but I would also like to offer it on PyPi

**Comment by PaulMcInnis** [comment]
It might also be wise to configure it as an action once we have better test coverage https://github.com/PaulMcInnis/JobFunnel/actions/new

**Comment by markkvdb** [comment]
What is missing exactly? Except for `setup.cfg` and the classifiers our package seems quite complete?

**Comment by PaulMcInnis** [comment]
I think this project is mostly there, however there is some work in simply confirming that we meet the specifications.
